version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports: 
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    networks:
      - node-network
  app:
      build: 
        context: .
      volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
      tty: true
      container_name: app
      depends_on:
        - db
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
      command: node index.js
      networks:
        - node-network
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=admin@123
    networks:
      - node-network

networks:
  node-network:
    driver: bridge